# Generated by Django 3.2.12 on 2022-03-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.studentprofile')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.subject')),
            ],
        ),
    ]
